### ISSUE TITLE
Instalar sequelize

### ISSUE THREAD

**Issue by fanyCaz** [fanyCaz/kindergarten-system#21]
https://sequelize.org/master/

**Comment by eduardosalaz** [comment]
## Instalar Sequelize y Probar Migraciones y Seedings:

1. El primer paso es naturalmente tener instalado [MariaDB](https://mariadb.org/download/)
2. Después tenemos que hacer los siguientes pasos dentro del proyecto:
3. `npm i --save sequelize`
4. `npm i --save mariadb`
5. `npm i --save-dev sequelize-cli`
6. No recuerdo si todas las instalaciones de node vienen con npx, sólo para comprobar pueden hacer: `npm install -g npx`
7. Si quieren realizar las migraciones deben de teclear `npx sequelize-cli db:migrate`, para propósitos de prueba decidí hacer una db que se llama **kinder_dev**, deben de crearla usando un gestor de SQL, ya sea la CLI o HeidiSQL
8. Para rellenar la tabla **Usuarios**, `npx sequelize-cli db:seed:all`
Mayor referencia la encuentran [aquí](https://sequelize.org/master/manual/migrations.html)
Una cosa más, el config.json dentro de config/ marca su usuario y contraseña para acceder a la base de datos, lo modifican a su caso.
