### ISSUE TITLE
Deploy (??)

### ISSUE THREAD

**Issue by eduardosalaz** [fanyCaz/kindergarten-system#84]
checar https://developers.cloudflare.com/pages/how-to/preview-with-cloudflare-tunnel a lo mejor

**Comment by eduardosalaz** [comment]
container

**Comment by fanyCaz** [comment]
Uso del cliente para prueba de usuario

**Comment by fanyCaz** [comment]
Se usó zoom con compartir el control de la pantalla.

Cambios requeridos:
- [ ] Servicios escogidos por el cliente deben ser los de la plataforma
- [ ] En formulario de cliente cambiar de Nombre a "Nombre de papá o mamá"
- [ ] Cambiar horas diarias, a "hora de entrada" y "hora de salida"
- [ ] Campo de edad en formulario del cliente no es necesario
- [ ] Se deben poner como obligatorios los campos de "nombre" y "número de emergencia"
- [ ] Si la edad del niño es mayor a  4 años, en el listado de niños,ponerlo en rojo.
